mod helpers;

use esk::config::ResolvedTarget;
use esk::targets::dotenv::DotenvTarget;
use esk::targets::{DeployTarget, SecretValue};
use helpers::*;
use zeroize::Zeroizing;

fn make_target(app: &str, env: &str) -> ResolvedTarget {
    ResolvedTarget {
        service: ".env".to_string(),
        app: Some(app.to_string()),
        environment: env.to_string(),
    }
}

fn make_secret(key: &str, value: &str, group: &str) -> SecretValue {
    SecretValue {
        key: key.to_string(),
        value: Zeroizing::new(value.to_string()),
        group: group.to_string(),
    }
}

#[test]
fn env_file_end_to_end() {
    let project = TestProject::with_store(ENV_ONLY_CONFIG).unwrap();
    let config = project.config().unwrap();
    std::fs::create_dir_all(project.root().join("apps/web")).unwrap();

    // Set secrets in the store
    let store = project.store().unwrap();
    store.set("MY_SECRET", "dev", "secret_dev").unwrap();
    store.set("OTHER_SECRET", "dev", "other_dev").unwrap();

    let target = DotenvTarget { config: &config };
    let secrets = vec![
        make_secret("MY_SECRET", "secret_dev", "General"),
        make_secret("OTHER_SECRET", "other_dev", "General"),
    ];
    let results = target.deploy_batch(&secrets, &make_target("web", "dev"));
    assert!(results.iter().all(|r| r.outcome.is_success()));

    let content = std::fs::read_to_string(project.root().join("apps/web/.env.local")).unwrap();
    assert!(content.contains("MY_SECRET=secret_dev"));
    assert!(content.contains("OTHER_SECRET=other_dev"));
    assert!(content.contains("# Auto-generated by esk"));
}

#[test]
fn env_file_multiple_groups() {
    let project = TestProject::with_store(ENV_ONLY_CONFIG).unwrap();
    let config = project.config().unwrap();
    std::fs::create_dir_all(project.root().join("apps/web")).unwrap();

    let target = DotenvTarget { config: &config };
    let secrets = vec![
        make_secret("A", "1", "Stripe"),
        make_secret("B", "2", "Convex"),
        make_secret("C", "3", "Resend"),
    ];
    let results = target.deploy_batch(&secrets, &make_target("web", "dev"));
    assert!(results.iter().all(|r| r.outcome.is_success()));

    let content = std::fs::read_to_string(project.root().join("apps/web/.env.local")).unwrap();
    assert!(content.contains("# === Stripe ==="));
    assert!(content.contains("# === Convex ==="));
    assert!(content.contains("# === Resend ==="));
}

#[test]
fn env_file_regeneration_replaces() {
    let project = TestProject::with_store(ENV_ONLY_CONFIG).unwrap();
    let config = project.config().unwrap();
    std::fs::create_dir_all(project.root().join("apps/web")).unwrap();

    let env_target = DotenvTarget { config: &config };
    let resolved = make_target("web", "dev");

    // First write
    let secrets1 = vec![make_secret("OLD_KEY", "old", "G")];
    env_target.deploy_batch(&secrets1, &resolved);

    // Second write with different secrets
    let secrets2 = vec![make_secret("NEW_KEY", "new", "G")];
    env_target.deploy_batch(&secrets2, &resolved);

    let content = std::fs::read_to_string(project.root().join("apps/web/.env.local")).unwrap();
    assert!(content.contains("NEW_KEY=new"));
    assert!(!content.contains("OLD_KEY")); // completely replaced
}
