mod helpers;

use esk::config::ResolvedTarget;
use esk::targets::env_file::EnvFileTarget;
use esk::targets::{DeployTarget, SecretValue};
use helpers::*;

fn make_target(app: &str, env: &str) -> ResolvedTarget {
    ResolvedTarget {
        service: "env".to_string(),
        app: Some(app.to_string()),
        environment: env.to_string(),
    }
}

#[test]
fn env_file_end_to_end() {
    let project = TestProject::with_store(ENV_ONLY_CONFIG).unwrap();
    let config = project.config().unwrap();
    std::fs::create_dir_all(project.root().join("apps/web")).unwrap();

    // Set secrets in the store
    let store = project.store().unwrap();
    store.set("MY_SECRET", "dev", "secret_dev").unwrap();
    store.set("OTHER_SECRET", "dev", "other_dev").unwrap();

    let target = EnvFileTarget { config: &config };
    let secrets = vec![
        SecretValue {
            key: "MY_SECRET".into(),
            value: "secret_dev".into(),
            group: "General".into(),
        },
        SecretValue {
            key: "OTHER_SECRET".into(),
            value: "other_dev".into(),
            group: "General".into(),
        },
    ];
    let results = target.deploy_batch(&secrets, &make_target("web", "dev"));
    assert!(results.iter().all(|r| r.outcome.is_success()));

    let content = std::fs::read_to_string(project.root().join("apps/web/.env.local")).unwrap();
    assert!(content.contains("MY_SECRET=secret_dev"));
    assert!(content.contains("OTHER_SECRET=other_dev"));
    assert!(content.contains("# Auto-generated by esk"));
}

#[test]
fn env_file_multiple_groups() {
    let project = TestProject::with_store(ENV_ONLY_CONFIG).unwrap();
    let config = project.config().unwrap();
    std::fs::create_dir_all(project.root().join("apps/web")).unwrap();

    let target = EnvFileTarget { config: &config };
    let secrets = vec![
        SecretValue {
            key: "A".into(),
            value: "1".into(),
            group: "Stripe".into(),
        },
        SecretValue {
            key: "B".into(),
            value: "2".into(),
            group: "Convex".into(),
        },
        SecretValue {
            key: "C".into(),
            value: "3".into(),
            group: "Resend".into(),
        },
    ];
    let results = target.deploy_batch(&secrets, &make_target("web", "dev"));
    assert!(results.iter().all(|r| r.outcome.is_success()));

    let content = std::fs::read_to_string(project.root().join("apps/web/.env.local")).unwrap();
    assert!(content.contains("# === Stripe ==="));
    assert!(content.contains("# === Convex ==="));
    assert!(content.contains("# === Resend ==="));
}

#[test]
fn env_file_regeneration_replaces() {
    let project = TestProject::with_store(ENV_ONLY_CONFIG).unwrap();
    let config = project.config().unwrap();
    std::fs::create_dir_all(project.root().join("apps/web")).unwrap();

    let env_target = EnvFileTarget { config: &config };
    let resolved = make_target("web", "dev");

    // First write
    let secrets1 = vec![SecretValue {
        key: "OLD_KEY".into(),
        value: "old".into(),
        group: "G".into(),
    }];
    env_target.deploy_batch(&secrets1, &resolved);

    // Second write with different secrets
    let secrets2 = vec![SecretValue {
        key: "NEW_KEY".into(),
        value: "new".into(),
        group: "G".into(),
    }];
    env_target.deploy_batch(&secrets2, &resolved);

    let content = std::fs::read_to_string(project.root().join("apps/web/.env.local")).unwrap();
    assert!(content.contains("NEW_KEY=new"));
    assert!(!content.contains("OLD_KEY")); // completely replaced
}
