use anyhow::Result;
use std::collections::BTreeSet;
use std::path::Path;

use crate::config::Config;

pub fn run(config: &Config, runtime: bool, output: Option<&str>) -> Result<()> {
    let keys = collect_keys(config);

    if keys.is_empty() {
        cliclack::log::warning("No secrets defined in config")?;
        return Ok(());
    }

    let default_name = if runtime { "env.ts" } else { "env.d.ts" };
    let out_path = match output {
        Some(p) => config.root.join(p),
        None => config.root.join(default_name),
    };

    let content = if runtime {
        generate_runtime(&keys)
    } else {
        generate_dts(&keys)
    };

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&out_path, content)?;

    let relative = out_path.strip_prefix(&config.root).unwrap_or(&out_path);

    cliclack::log::success(format!(
        "Wrote {} secrets to {}",
        keys.len(),
        relative.display()
    ))?;

    if !is_gitignored(&config.root, relative) {
        cliclack::log::info(format!(
            "Consider adding {} to .gitignore",
            relative.display()
        ))?;
    }

    Ok(())
}

fn collect_keys(config: &Config) -> BTreeSet<String> {
    let mut keys = BTreeSet::new();
    for group in config.secrets.values() {
        for key in group.keys() {
            keys.insert(key.clone());
        }
    }
    keys
}

fn generate_dts(keys: &BTreeSet<String>) -> String {
    let mut out = String::from("// Generated by esk — do not edit\n");
    out.push_str("declare namespace NodeJS {\n");
    out.push_str("  interface ProcessEnv {\n");
    for key in keys {
        out.push_str(&format!("    {key}: string;\n"));
    }
    out.push_str("  }\n");
    out.push_str("}\n");
    out
}

fn generate_runtime(keys: &BTreeSet<String>) -> String {
    let mut out = String::from("// Generated by esk — do not edit\n");
    out.push_str("function requireEnv(key: string): string {\n");
    out.push_str("  const value = process.env[key];\n");
    out.push_str("  if (value === undefined || value === \"\") {\n");
    out.push_str("    throw new Error(`Missing required environment variable: ${key}`);\n");
    out.push_str("  }\n");
    out.push_str("  return value;\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("export const env = {\n");
    for key in keys {
        out.push_str(&format!("  {key}: requireEnv(\"{key}\"),\n"));
    }
    out.push_str("} as const;\n");
    out
}

fn is_gitignored(root: &Path, relative: &Path) -> bool {
    let gitignore_path = root.join(".gitignore");
    let Ok(content) = std::fs::read_to_string(&gitignore_path) else {
        return false;
    };
    let filename = relative.file_name().unwrap_or_default().to_string_lossy();
    let full_path = relative.to_string_lossy();
    content.lines().any(|line| {
        let trimmed = line.trim();
        !trimmed.is_empty()
            && !trimmed.starts_with('#')
            && (pattern_matches(trimmed, &filename) || pattern_matches(trimmed, &full_path))
    })
}

fn pattern_matches(pattern: &str, path: &str) -> bool {
    if let Some(suffix) = pattern.strip_prefix('*') {
        path.ends_with(suffix)
    } else if let Some(prefix) = pattern.strip_suffix('*') {
        path.starts_with(prefix)
    } else {
        pattern == path
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn config_with_secrets(
        secrets: BTreeMap<String, BTreeMap<String, crate::config::SecretDef>>,
    ) -> Config {
        Config {
            project: "test".to_string(),
            environments: vec!["dev".to_string(), "prod".to_string()],
            apps: BTreeMap::new(),
            targets: Default::default(),
            remotes: BTreeMap::new(),
            secrets,
            root: std::path::PathBuf::from("/tmp"),
        }
    }

    fn secret_def() -> crate::config::SecretDef {
        crate::config::SecretDef {
            description: None,
            targets: BTreeMap::new(),
        }
    }

    #[test]
    fn collect_keys_unions_across_groups() {
        let mut secrets = BTreeMap::new();
        let mut group_a = BTreeMap::new();
        group_a.insert("ALPHA".to_string(), secret_def());
        group_a.insert("SHARED".to_string(), secret_def());
        secrets.insert("A".to_string(), group_a);

        let mut group_b = BTreeMap::new();
        group_b.insert("BETA".to_string(), secret_def());
        group_b.insert("SHARED".to_string(), secret_def());
        secrets.insert("B".to_string(), group_b);

        let config = config_with_secrets(secrets);
        let keys = collect_keys(&config);

        assert_eq!(keys.len(), 3);
        assert!(keys.contains("ALPHA"));
        assert!(keys.contains("BETA"));
        assert!(keys.contains("SHARED"));
    }

    #[test]
    fn collect_keys_empty_config() {
        let config = config_with_secrets(BTreeMap::new());
        assert!(collect_keys(&config).is_empty());
    }

    #[test]
    fn dts_output_format() {
        let mut keys = BTreeSet::new();
        keys.insert("A_KEY".to_string());
        keys.insert("B_KEY".to_string());

        let output = generate_dts(&keys);
        assert!(output.starts_with("// Generated by esk"));
        assert!(output.contains("declare namespace NodeJS"));
        assert!(output.contains("interface ProcessEnv"));
        assert!(output.contains("A_KEY: string;"));
        assert!(output.contains("B_KEY: string;"));
    }

    #[test]
    fn runtime_output_format() {
        let mut keys = BTreeSet::new();
        keys.insert("DB_URL".to_string());

        let output = generate_runtime(&keys);
        assert!(output.starts_with("// Generated by esk"));
        assert!(output.contains("function requireEnv"));
        assert!(output.contains("export const env ="));
        assert!(output.contains("DB_URL: requireEnv(\"DB_URL\")"));
        assert!(output.contains("as const;"));
    }

    #[test]
    fn keys_are_sorted() {
        let mut keys = BTreeSet::new();
        keys.insert("ZEBRA".to_string());
        keys.insert("ALPHA".to_string());
        keys.insert("MIDDLE".to_string());

        let output = generate_dts(&keys);
        let alpha_pos = output.find("ALPHA").unwrap();
        let middle_pos = output.find("MIDDLE").unwrap();
        let zebra_pos = output.find("ZEBRA").unwrap();
        assert!(alpha_pos < middle_pos);
        assert!(middle_pos < zebra_pos);
    }

    #[test]
    fn gitignore_match() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "env.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("env.d.ts")));
        assert!(!is_gitignored(dir.path(), Path::new("other.ts")));
    }

    #[test]
    fn gitignore_missing() {
        let dir = tempfile::tempdir().unwrap();
        assert!(!is_gitignored(dir.path(), Path::new("env.d.ts")));
    }

    #[test]
    fn gitignore_glob_patterns() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "*.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("env.d.ts")));
        assert!(!is_gitignored(dir.path(), Path::new("env.ts")));
    }

    #[test]
    fn gitignore_matches_filename_in_subpath() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "env.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("types/env.d.ts")));
    }

    #[test]
    fn gitignore_comments_and_blanks_ignored() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "# comment\n\nenv.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("env.d.ts")));
        assert!(!is_gitignored(dir.path(), Path::new("# comment")));
    }
}
