use anyhow::Result;
use std::collections::BTreeSet;
use std::path::Path;

use crate::config::Config;
use crate::validate::Format;

struct SecretMeta {
    key: String,
    format: Option<Format>,
    optional: bool,
    enum_values: Option<Vec<String>>,
}

pub fn run(config: &Config, runtime: bool, output: Option<&str>) -> Result<()> {
    let metas = collect_secret_metas(config);

    if metas.is_empty() {
        cliclack::log::warning("No secrets defined in config")?;
        return Ok(());
    }

    let default_name = if runtime { "env.ts" } else { "env.d.ts" };
    let out_path = match output {
        Some(p) => config.root.join(p),
        None => config.root.join(default_name),
    };

    let content = if runtime {
        generate_runtime(&metas)
    } else {
        generate_dts(&metas)
    };

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&out_path, content)?;

    let relative = out_path.strip_prefix(&config.root).unwrap_or(&out_path);

    cliclack::log::success(format!(
        "Wrote {} secrets to {}",
        metas.len(),
        relative.display()
    ))?;

    if !is_gitignored(&config.root, relative) {
        cliclack::log::info(format!(
            "Consider adding {} to .gitignore",
            relative.display()
        ))?;
    }

    Ok(())
}

fn collect_secret_metas(config: &Config) -> Vec<SecretMeta> {
    let mut seen = BTreeSet::new();
    let mut metas = Vec::new();
    for group in config.secrets.values() {
        for (key, def) in group {
            if seen.insert(key.clone()) {
                let (format, optional, enum_values) = match &def.validate {
                    Some(v) => {
                        let enums = v
                            .enum_values
                            .as_ref()
                            .and_then(|raw| crate::validate::resolve_enum_values(raw).ok());
                        (v.format, v.optional, enums)
                    }
                    None => (None, false, None),
                };
                metas.push(SecretMeta {
                    key: key.clone(),
                    format,
                    optional,
                    enum_values,
                });
            }
        }
    }
    metas.sort_by(|a, b| a.key.cmp(&b.key));
    metas
}

fn generate_dts(metas: &[SecretMeta]) -> String {
    let mut out = String::from("// Generated by esk — do not edit\n");
    out.push_str("declare namespace NodeJS {\n");
    out.push_str("  interface ProcessEnv {\n");
    for m in metas {
        if let Some(ref values) = m.enum_values {
            let union = values
                .iter()
                .map(|v| format!("\"{}\"", v))
                .collect::<Vec<_>>()
                .join(" | ");
            if m.optional {
                out.push_str(&format!("    {}?: {} | undefined;\n", m.key, union));
            } else {
                out.push_str(&format!("    {}: {};\n", m.key, union));
            }
        } else if m.optional {
            out.push_str(&format!("    {}?: string | undefined;\n", m.key));
        } else {
            out.push_str(&format!("    {}: string;\n", m.key));
        }
    }
    out.push_str("  }\n");
    out.push_str("}\n");
    out
}

fn generate_runtime(metas: &[SecretMeta]) -> String {
    let mut out = String::from("// Generated by esk — do not edit\n");

    // Determine which helpers are needed
    let mut needed_helpers: BTreeSet<&str> = BTreeSet::new();
    for m in metas {
        if m.optional {
            // Optional secrets use process.env directly
            continue;
        }
        match m.format {
            Some(Format::Integer) => {
                needed_helpers.insert("envInt");
            }
            Some(Format::Number) => {
                needed_helpers.insert("envFloat");
            }
            Some(Format::Boolean) => {
                needed_helpers.insert("envBool");
            }
            Some(Format::Json) => {
                needed_helpers.insert("envJson");
            }
            _ => {
                needed_helpers.insert("requireEnv");
            }
        }
    }

    // Emit only the helpers that are used
    if needed_helpers.contains("requireEnv") {
        out.push_str("function requireEnv(key: string): string {\n");
        out.push_str("  const value = process.env[key];\n");
        out.push_str("  if (value === undefined || value === \"\") {\n");
        out.push_str("    throw new Error(`Missing required environment variable: ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  return value;\n");
        out.push_str("}\n");
        out.push('\n');
    }

    if needed_helpers.contains("envInt") {
        out.push_str("function envInt(key: string): number {\n");
        out.push_str("  const value = process.env[key];\n");
        out.push_str("  if (value === undefined || value === \"\") {\n");
        out.push_str("    throw new Error(`Missing required environment variable: ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  const num = parseInt(value, 10);\n");
        out.push_str("  if (isNaN(num)) {\n");
        out.push_str("    throw new Error(`Expected integer for ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  return num;\n");
        out.push_str("}\n");
        out.push('\n');
    }

    if needed_helpers.contains("envFloat") {
        out.push_str("function envFloat(key: string): number {\n");
        out.push_str("  const value = process.env[key];\n");
        out.push_str("  if (value === undefined || value === \"\") {\n");
        out.push_str("    throw new Error(`Missing required environment variable: ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  const num = parseFloat(value);\n");
        out.push_str("  if (isNaN(num)) {\n");
        out.push_str("    throw new Error(`Expected number for ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  return num;\n");
        out.push_str("}\n");
        out.push('\n');
    }

    if needed_helpers.contains("envBool") {
        out.push_str("function envBool(key: string): boolean {\n");
        out.push_str("  const value = process.env[key]?.toLowerCase();\n");
        out.push_str("  if (value === undefined || value === \"\") {\n");
        out.push_str("    throw new Error(`Missing required environment variable: ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  return [\"true\", \"1\", \"yes\"].includes(value);\n");
        out.push_str("}\n");
        out.push('\n');
    }

    if needed_helpers.contains("envJson") {
        out.push_str("function envJson(key: string): unknown {\n");
        out.push_str("  const value = process.env[key];\n");
        out.push_str("  if (value === undefined || value === \"\") {\n");
        out.push_str("    throw new Error(`Missing required environment variable: ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("  try {\n");
        out.push_str("    return JSON.parse(value);\n");
        out.push_str("  } catch {\n");
        out.push_str("    throw new Error(`Invalid JSON for environment variable ${key}`);\n");
        out.push_str("  }\n");
        out.push_str("}\n");
        out.push('\n');
    }

    out.push_str("export const env = {\n");
    for m in metas {
        if m.optional {
            out.push_str(&format!("  {}: process.env.{},\n", m.key, m.key));
        } else {
            match m.format {
                Some(Format::Integer) => {
                    out.push_str(&format!("  {}: envInt(\"{}\"),\n", m.key, m.key));
                }
                Some(Format::Number) => {
                    out.push_str(&format!("  {}: envFloat(\"{}\"),\n", m.key, m.key));
                }
                Some(Format::Boolean) => {
                    out.push_str(&format!("  {}: envBool(\"{}\"),\n", m.key, m.key));
                }
                Some(Format::Json) => {
                    out.push_str(&format!("  {}: envJson(\"{}\"),\n", m.key, m.key));
                }
                _ => {
                    out.push_str(&format!("  {}: requireEnv(\"{}\"),\n", m.key, m.key));
                }
            }
        }
    }
    out.push_str("} as const;\n");
    out
}

fn is_gitignored(root: &Path, relative: &Path) -> bool {
    let gitignore_path = root.join(".gitignore");
    let Ok(content) = std::fs::read_to_string(&gitignore_path) else {
        return false;
    };
    let filename = relative.file_name().unwrap_or_default().to_string_lossy();
    let full_path = relative.to_string_lossy();
    content.lines().any(|line| {
        let trimmed = line.trim();
        !trimmed.is_empty()
            && !trimmed.starts_with('#')
            && (pattern_matches(trimmed, &filename) || pattern_matches(trimmed, &full_path))
    })
}

fn pattern_matches(pattern: &str, path: &str) -> bool {
    if let Some(suffix) = pattern.strip_prefix('*') {
        path.ends_with(suffix)
    } else if let Some(prefix) = pattern.strip_suffix('*') {
        path.starts_with(prefix)
    } else {
        pattern == path
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn collect_keys(config: &Config) -> BTreeSet<String> {
        collect_secret_metas(config)
            .into_iter()
            .map(|m| m.key)
            .collect()
    }

    fn config_with_secrets(
        secrets: BTreeMap<String, BTreeMap<String, crate::config::SecretDef>>,
    ) -> Config {
        Config {
            project: "test".to_string(),
            environments: vec!["dev".to_string(), "prod".to_string()],
            apps: BTreeMap::new(),
            targets: Default::default(),
            remotes: BTreeMap::new(),
            secrets,
            root: std::path::PathBuf::from("/tmp"),
        }
    }

    fn secret_def() -> crate::config::SecretDef {
        crate::config::SecretDef {
            description: None,
            targets: BTreeMap::new(),
            validate: None,
            required: Default::default(),
            allow_empty: false,
        }
    }

    fn secret_def_with_validate(v: crate::validate::Validation) -> crate::config::SecretDef {
        crate::config::SecretDef {
            description: None,
            targets: BTreeMap::new(),
            validate: Some(v),
            required: Default::default(),
            allow_empty: false,
        }
    }

    #[test]
    fn collect_keys_unions_across_groups() {
        let mut secrets = BTreeMap::new();
        let mut group_a = BTreeMap::new();
        group_a.insert("ALPHA".to_string(), secret_def());
        group_a.insert("SHARED".to_string(), secret_def());
        secrets.insert("A".to_string(), group_a);

        let mut group_b = BTreeMap::new();
        group_b.insert("BETA".to_string(), secret_def());
        group_b.insert("SHARED".to_string(), secret_def());
        secrets.insert("B".to_string(), group_b);

        let config = config_with_secrets(secrets);
        let keys = collect_keys(&config);

        assert_eq!(keys.len(), 3);
        assert!(keys.contains("ALPHA"));
        assert!(keys.contains("BETA"));
        assert!(keys.contains("SHARED"));
    }

    #[test]
    fn collect_keys_empty_config() {
        let config = config_with_secrets(BTreeMap::new());
        assert!(collect_keys(&config).is_empty());
    }

    #[test]
    fn dts_output_format() {
        let metas = vec![
            SecretMeta {
                key: "A_KEY".to_string(),
                format: None,
                optional: false,
                enum_values: None,
            },
            SecretMeta {
                key: "B_KEY".to_string(),
                format: None,
                optional: false,
                enum_values: None,
            },
        ];

        let output = generate_dts(&metas);
        assert!(output.starts_with("// Generated by esk"));
        assert!(output.contains("declare namespace NodeJS"));
        assert!(output.contains("interface ProcessEnv"));
        assert!(output.contains("A_KEY: string;"));
        assert!(output.contains("B_KEY: string;"));
    }

    #[test]
    fn runtime_output_format() {
        let metas = vec![SecretMeta {
            key: "DB_URL".to_string(),
            format: None,
            optional: false,
            enum_values: None,
        }];

        let output = generate_runtime(&metas);
        assert!(output.starts_with("// Generated by esk"));
        assert!(output.contains("function requireEnv"));
        assert!(output.contains("export const env ="));
        assert!(output.contains("DB_URL: requireEnv(\"DB_URL\")"));
        assert!(output.contains("as const;"));
    }

    #[test]
    fn keys_are_sorted() {
        let metas = vec![
            SecretMeta {
                key: "ZEBRA".to_string(),
                format: None,
                optional: false,
                enum_values: None,
            },
            SecretMeta {
                key: "ALPHA".to_string(),
                format: None,
                optional: false,
                enum_values: None,
            },
            SecretMeta {
                key: "MIDDLE".to_string(),
                format: None,
                optional: false,
                enum_values: None,
            },
        ];

        // collect_secret_metas sorts, but generate_dts takes pre-sorted slice.
        // Test via dts output order:
        let mut sorted = metas;
        sorted.sort_by(|a, b| a.key.cmp(&b.key));
        let output = generate_dts(&sorted);
        let alpha_pos = output.find("ALPHA").unwrap();
        let middle_pos = output.find("MIDDLE").unwrap();
        let zebra_pos = output.find("ZEBRA").unwrap();
        assert!(alpha_pos < middle_pos);
        assert!(middle_pos < zebra_pos);
    }

    #[test]
    fn gitignore_match() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "env.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("env.d.ts")));
        assert!(!is_gitignored(dir.path(), Path::new("other.ts")));
    }

    #[test]
    fn gitignore_missing() {
        let dir = tempfile::tempdir().unwrap();
        assert!(!is_gitignored(dir.path(), Path::new("env.d.ts")));
    }

    #[test]
    fn gitignore_glob_patterns() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "*.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("env.d.ts")));
        assert!(!is_gitignored(dir.path(), Path::new("env.ts")));
    }

    #[test]
    fn gitignore_matches_filename_in_subpath() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "env.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("types/env.d.ts")));
    }

    #[test]
    fn gitignore_comments_and_blanks_ignored() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "# comment\n\nenv.d.ts\n").unwrap();
        assert!(is_gitignored(dir.path(), Path::new("env.d.ts")));
        assert!(!is_gitignored(dir.path(), Path::new("# comment")));
    }

    #[test]
    fn generate_dts_enum_union_type() {
        let metas = vec![SecretMeta {
            key: "NODE_ENV".to_string(),
            format: None,
            optional: false,
            enum_values: Some(vec![
                "development".to_string(),
                "staging".to_string(),
                "production".to_string(),
            ]),
        }];
        let output = generate_dts(&metas);
        assert!(output.contains("NODE_ENV: \"development\" | \"staging\" | \"production\";"));
    }

    #[test]
    fn generate_dts_optional_field() {
        let metas = vec![SecretMeta {
            key: "FEATURE_FLAG".to_string(),
            format: Some(Format::String),
            optional: true,
            enum_values: None,
        }];
        let output = generate_dts(&metas);
        assert!(output.contains("FEATURE_FLAG?: string | undefined;"));
    }

    #[test]
    fn generate_runtime_emits_typed_helpers() {
        let metas = vec![
            SecretMeta {
                key: "PORT".to_string(),
                format: Some(Format::Integer),
                optional: false,
                enum_values: None,
            },
            SecretMeta {
                key: "URL".to_string(),
                format: Some(Format::Url),
                optional: false,
                enum_values: None,
            },
        ];
        let output = generate_runtime(&metas);
        assert!(output.contains("function envInt("));
        assert!(output.contains("PORT: envInt(\"PORT\")"));
        assert!(output.contains("function requireEnv("));
        assert!(output.contains("URL: requireEnv(\"URL\")"));
    }

    #[test]
    fn generate_runtime_omits_unused_helpers() {
        let metas = vec![SecretMeta {
            key: "PORT".to_string(),
            format: Some(Format::Integer),
            optional: false,
            enum_values: None,
        }];
        let output = generate_runtime(&metas);
        assert!(output.contains("function envInt("));
        assert!(!output.contains("function requireEnv("));
        assert!(!output.contains("function envBool("));
        assert!(!output.contains("function envFloat("));
        assert!(!output.contains("function envJson("));
    }

    #[test]
    fn generate_runtime_optional_uses_process_env() {
        let metas = vec![SecretMeta {
            key: "FEATURE".to_string(),
            format: Some(Format::Boolean),
            optional: true,
            enum_values: None,
        }];
        let output = generate_runtime(&metas);
        assert!(output.contains("FEATURE: process.env.FEATURE"));
        // Optional doesn't need envBool helper
        assert!(!output.contains("function envBool("));
    }

    #[test]
    fn collect_secret_metas_extracts_validation() {
        let mut secrets = BTreeMap::new();
        let mut group = BTreeMap::new();
        group.insert(
            "PORT".to_string(),
            secret_def_with_validate(crate::validate::Validation {
                format: Some(Format::Integer),
                ..Default::default()
            }),
        );
        group.insert("PLAIN".to_string(), secret_def());
        secrets.insert("General".to_string(), group);

        let config = config_with_secrets(secrets);
        let metas = collect_secret_metas(&config);

        let plain = metas.iter().find(|m| m.key == "PLAIN").unwrap();
        assert!(plain.format.is_none());

        let port = metas.iter().find(|m| m.key == "PORT").unwrap();
        assert_eq!(port.format, Some(Format::Integer));
    }
}
