use anyhow::{Context, Result};
use std::collections::BTreeMap;
use tempfile::NamedTempFile;

use crate::adapters::{SecretValue, SyncAdapter, SyncResult};
use crate::config::{Config, ResolvedTarget};

pub struct EnvFileAdapter<'a> {
    pub config: &'a Config,
}

impl<'a> SyncAdapter for EnvFileAdapter<'a> {
    fn name(&self) -> &str {
        "env"
    }

    fn sync_secret(&self, _key: &str, _value: &str, _target: &ResolvedTarget) -> Result<()> {
        // Env adapter always uses sync_batch — individual sync is a no-op
        // because we need to regenerate the entire file atomically
        Ok(())
    }

    /// Override: regenerate the entire env file for this (app, env) pair.
    fn sync_batch(&self, secrets: &[SecretValue], target: &ResolvedTarget) -> Vec<SyncResult> {
        let app = match &target.app {
            Some(a) => a,
            None => {
                return secrets
                    .iter()
                    .map(|s| SyncResult {
                        key: s.key.clone(),
                        target: target.clone(),
                        success: false,
                        error: Some("env adapter requires an app".to_string()),
                    })
                    .collect();
            }
        };

        match self.write_env_file(app, &target.environment, secrets) {
            Ok(()) => secrets
                .iter()
                .map(|s| SyncResult {
                    key: s.key.clone(),
                    target: target.clone(),
                    success: true,
                    error: None,
                })
                .collect(),
            Err(e) => secrets
                .iter()
                .map(|s| SyncResult {
                    key: s.key.clone(),
                    target: target.clone(),
                    success: false,
                    error: Some(e.to_string()),
                })
                .collect(),
        }
    }
}

impl<'a> EnvFileAdapter<'a> {
    fn write_env_file(&self, app: &str, env: &str, secrets: &[SecretValue]) -> Result<()> {
        let path = self.config.resolve_env_path(app, env)?;

        // Group secrets by vendor, maintaining sorted order
        let mut by_vendor: BTreeMap<&str, Vec<(&str, &str)>> = BTreeMap::new();
        for secret in secrets {
            by_vendor
                .entry(&secret.vendor)
                .or_default()
                .push((&secret.key, &secret.value));
        }

        let mut content = String::new();
        content.push_str("# Auto-generated by lockbox — do not edit manually\n");
        content.push_str("#\n");
        content.push_str("# Update secrets:  lockbox set <KEY> --env <ENV>\n");
        content.push_str("# Regenerate file: lockbox sync --env <ENV>\n");

        for (vendor, mut entries) in by_vendor {
            entries.sort_by_key(|(k, _)| *k);
            content.push('\n');
            content.push_str(&format!("# === {vendor} ===\n"));
            for (key, value) in entries {
                content.push_str(&format!("{key}={value}\n"));
            }
        }

        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("failed to create directory {}", parent.display()))?;
        }

        // Atomic write
        let dir = path.parent().context("env path has no parent")?;
        let tmp = NamedTempFile::new_in(dir)?;
        std::fs::write(tmp.path(), &content)?;
        tmp.persist(&path)
            .with_context(|| format!("failed to write {}", path.display()))?;

        Ok(())
    }
}

